# Generated by Django 4.1.3 on 2022-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RentACar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cars', models.TextField()),
                ('description', models.TextField()),
                ('logo', models.URLField()),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
